version: '3'
services:
  webserver:
    image: nginx
    ports:
      - '83:83'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./web/:/var/www/html
    depends_on:
      - php
    networks:
      - mynetwork

  php:
    image: php:latest
    volumes:
      - ./web/:/var/www/html
    networks:
      - mynetwork

networks:
  mynetwork:
